SDK-667 : Limit VCS info to 64kb
TamsilAmani/browserstack-cypress-cli pull request #1
Opened 2024-05-20 08:13 UTC by TamsilAmani

Limiting the total size of VCS info to 64 Kb.

JIRA: https://browserstack.atlassian.net/browse/SDK-667

2024-05-21 12:37 UTC, sauravdas1997 commented on bin/helpers/helper.js
> +};
EOF

2024-05-21 12:37 UTC, sauravdas1997 commented on bin/helpers/helper.js
> +    logger.debug(`Error while truncating field, nothing was truncated here: ${error}`, true, error);
why are we logging the same line twice?

2024-05-23 03:59 UTC, TamsilAmani commented on bin/helpers/helper.js
> +    logger.debug(`Error while truncating field, nothing was truncated here: ${error}`, true, error);
We can remove `exports.debug`

2024-05-23 09:24 UTC, sauravdas1997 approved these changes

2024-05-23 11:36 UTC, 07souravkunda requested changes

2024-05-23 11:36 UTC, 07souravkunda commented on bin/helpers/helper.js
> +    gitMetaData.commit_message = truncatedCommitMessage;
```suggestion
    gitMetaData.commit_message = exports.truncateString(gitMetaData.commit_message, truncateSize);;
```

2024-05-27 05:44 UTC, 07souravkunda approved these changes

2024-05-29 07:39 UTC, asambstack approved these changes

2024-05-30 13:20 UTC, merged